version: '3'

services:
  fastapi-app:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  streamlit-app:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi-app
    environment:
      - FASTAPI_URL=http://fastapi-app:8000